### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by LaggedHosting** [sensson/whmcs-moneybird#27]
Since a day or 2 the module is getting an unautorized messaged.

I checked the module, was setup correctly. Checked the api, was also still good.
Made a new api in Moneybird, didnt work either.

Reinstalled the module, yet no succes.

This is the error code:
`GuzzleHttp\Exception\ClientException: Client error: `GET https://moneybird.com/api/v2/MYADMINISTRATIONID/ledger_accounts.json` resulted in a `401 Unauthorized` response:
{"error":"access token invalid","symbolic":{"request":"invalid_grant"}}
in /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/whmcs/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/whmcs/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(231): GuzzleHttp\Client->send()
#11 /var/www/whmcs/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/FindAll.php(35): Picqer\Financials\Moneybird\Connection->get()
#12 /var/www/whmcs/modules/addons/moneybird/lib/Controllers/Admin/LedgerMappingController.php(24): Picqer\Financials\Moneybird\Entities\LedgerAccount->getAll()
#13 /var/www/whmcs/modules/addons/moneybird/lib/Core/Pages.php(33): WHMCS\Module\Addon\Moneybird\Controllers\Admin\LedgerMappingController->get()
#14 /var/www/whmcs/modules/addons/moneybird/moneybird.php(251): WHMCS\Module\Addon\Moneybird\Core\Pages->get()
#15 /var/www/whmcs/admin/addonmodules.php(0): moneybird_output()
#16 {main}
Next Picqer\Financials\Moneybird\Exceptions\ApiException: Error 401: {"error":"access token invalid","symbolic":{"request":"invalid_grant"}} in /var/www/whmcs/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php:527
Stack trace:
#0 /var/www/whmcs/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(243): Picqer\Financials\Moneybird\Connection->parseExceptionForErrorMessages()
#1 /var/www/whmcs/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/FindAll.php(35): Picqer\Financials\Moneybird\Connection->get()
#2 /var/www/whmcs/modules/addons/moneybird/lib/Controllers/Admin/LedgerMappingController.php(24): Picqer\Financials\Moneybird\Entities\LedgerAccount->getAll()
#3 /var/www/whmcs/modules/addons/moneybird/lib/Core/Pages.php(33): WHMCS\Module\Addon\Moneybird\Controllers\Admin\LedgerMappingController->get()
#4 /var/www/whmcs/modules/addons/moneybird/moneybird.php(251): WHMCS\Module\Addon\Moneybird\Core\Pages->get()
#5 /var/www/whmcs/admin/addonmodules.php(0): moneybird_output()
#6 {main}`

I checked the token, it is valid.

**Comment by LaggedHosting** [comment]
Nevermind. Refreshed the access token once more, and it suddenly works.

What broke it though, that is a good question.
